stages:
  - check
  - documentation
  - quality
  - build
  - unit_test
  - active_tests

variables:
  GIT_STRATEGY: clone
  TIMEOUT: 10m

check_plantuml:
  stage: check
  script:
    - |
      if ! command -v plantuml &> /dev/null; then
        echo "Error: PlantUML is not installed."
        exit 1
      else
        echo "PlantUML is installed!"
      fi

docs:
  stage: documentation
  script:
    - make docs
  artifacts:
    paths:
      - docs/code/src

styleCheck:
  stage: quality
  script:
    - make style

staticAnalysis:
  stage: quality
  script:
    - make static

buildTests:
  stage: build
  script:
    - make test_dragonSlayer
  artifacts:
    paths:
      - dragonSlayer

unitTests:
  stage: unit_test
  script:
    - test_dragonSlayer

memoryLeaks:
  stage: active_tests
  script:
    - make memcheck