stages:
  - quality
  - build

variables:
  GIT_STRATEGY: clone
  TIMEOUT: 10m

styleCheck:
  stage: quality
  script:
    - make style

staticAnalysis:
  stage: quality
  script:
    - make static

buildTests:
  stage: build
  script:
    - sudo apt-get update -qq
    - sudo apt-get install -y libncurses-dev
    - make
  artifacts:
    paths:
      - dragonSlayer
