stages:
  - quality
  - build
  - unit_test
  - active_tests

variables:
  GIT_STRATEGY: clone
  TIMEOUT: 10m

styleCheck:
  stage: quality
  script:
    - make style

staticAnalysis:
  stage: quality
  script:
    - make static

buildTests:
  stage: build
  script:
    - make test_dragonSlayer
  artifacts:
    paths:
      - dragonSlayer

unitTests:
  stage: unit_test
  script:
    - test_dragonSlayer

memoryLeaks:
  stage: active_tests
  script:
    - make memcheck