name: DragonSlayer Test Pipeline
run-name: ${{ github.actor }} is running a test on DragonSlayer game
on:
  push:
    branches:
      - main

jobs:
  combined:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck


      - name: Install cpplint
        run: sudo apt-get install -y python3-pip && pip3 install cpplint

      - name: Install doxygen
        run: sudo apt-get install -y doxygen

      - name: Make Documentation
        run: make docs

      - name: Style Check
        run: make style

      - name: Static Analysis
        run: make static

      - name: Build Tests
        run: make test_dragonSlayer

      - name: Run Unit Tests
        run: ./test_dragonSlayer

      - name: Run Coverage
        run: make coverage


